# Generated by Django 5.1.7 on 2025-04-07 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('aproximate_price', models.IntegerField(default=1, verbose_name='Приблизна ціна')),
                ('status', models.CharField(choices=[('done', 'Виконано'), ('in_progress', 'Виконується'), ('in_search', 'В пошуку')], max_length=15)),
                ('urgency', models.CharField(choices=[('висока', 'Висока'), ('середня', 'Середня'), ('низька', 'Низька')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='authentication.userprofile')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_req', to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerViewedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_requests', to='volunteer_app.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'req'), name='unique_user_req')],
            },
        ),
    ]
