# Generated by Django 5.1.7 on 2025-04-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_category'),
        ('volunteer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='request',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_req', to='authentication.userprofile'),
        ),
    ]
