# Generated by Django 5.1.7 on 2025-04-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('volunteer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='volunteerviewedrequest',
            name='unique_user_request',
        ),
        migrations.RenameField(
            model_name='volunteerviewedrequest',
            old_name='request',
            new_name='req',
        ),
        migrations.AddConstraint(
            model_name='volunteerviewedrequest',
            constraint=models.UniqueConstraint(fields=('user', 'req'), name='unique_user_req'),
        ),
    ]
