# Generated by Django 5.1.7 on 2025-04-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='confidence_threshold',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='detectionconfig',
            name='iou_threshold',
            field=models.FloatField(default=0.45),
        ),
        migrations.DeleteModel(
            name='SegmentationMask',
        ),
    ]
