# Generated by Django 5.1.7 on 2025-04-07 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('military', 'Military'), ('infrastructure', 'Infrastructure'), ('residential', 'Residential'), ('hazard', 'Hazard'), ('other', 'Other')], default='other', max_length=20)),
                ('verification', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('ai-detected', 'AI Detected')], default='unverified', max_length=20)),
                ('confidence', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('verified_only', 'Verified Users Only')], default='public', max_length=20)),
                ('object_detection', models.BooleanField(default=False)),
                ('camouflage_detection', models.BooleanField(default=False)),
                ('request_verification', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarkerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.marker')),
            ],
        ),
    ]
