# Generated by Django 5.1.7 on 2025-04-07 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='comment_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marker',
            name='damage_assessment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marker',
            name='thermal_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marker',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='marker_upvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='marker',
            name='verification',
            field=models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('ai-detected', 'AI Detected'), ('disputed', 'Disputed'), ('pending', 'Pending')], default='unverified', max_length=20),
        ),
        migrations.CreateModel(
            name='MarkerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='content.marker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
