# Generated by Django 5.1.7 on 2025-04-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('soldier', 'Військовий(-а)'), ('volunteer', 'Волонтер(-ка)')], max_length=9, null=True),
        ),
    ]
