# Generated by Django 5.1.7 on 2025-04-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_userprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(blank=True, choices=[('soldier', 'Військовий(-а)'), ('volunteer', 'Волонтер(-ка)'), ('both', 'Волонтер(-ка) та військовий(-а)')], max_length=9, null=True),
        ),
    ]
