# Generated by Django 5.1.7 on 2025-04-05 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='MapLayer',
        ),
    ]
